<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Carrito.aspx.cs" Inherits="Vistas.Carrito" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 212px;
        }
        .auto-style3 {
            text-align: right;
        }
        .auto-style4 {
            text-align: center;
            width: 407px;
        }
        .auto-style5 {
            height: 24px;
        }
        .auto-style7 {
            height: 24px;
            width: 37px;
        }
        .auto-style8 {
            width: 37px;
        }
        .auto-style9 {
            width: 37px;
            height: 232px;
        }
        .auto-style11 {
            height: 232px;
        }
        .auto-style13 {
            height: 232px;
            width: 623px;
            text-align: center;
        }
        .auto-style14 {
            height: 24px;
            width: 623px;
        }
        .auto-style16 {
            text-align: center;
            width: 360px;
        }
        .auto-style17 {
            margin-left: 0px;
        }
        .auto-style18 {
            width: 100%;
            height: 64px;
        }
        .auto-style19 {
            font-size: large;
        }
        .auto-style22 {
            width: 37px;
            height: 30px;
        }
        .auto-style23 {
            text-align: center;
            width: 623px;
            height: 30px;
        }
        .auto-style24 {
            text-align: right;
            height: 30px;
        }
        .auto-style25 {
            text-align: center;
            width: 623px;
        }
        .auto-style26 {
            text-align: center;
            width: 295px;
        }
        .auto-style27 {
            text-align: center;
            width: 314px;
        }
    </style>
</head>
    
<body style="background-image: url(https://cdn.wallpapersafari.com/34/54/2gc14T.jpg);background-size:cover;">
    <form id="form1" runat="server">
       <div class="navbar" style="background-color: #e3f2fd; margin-right:30px;margin-left:30px; border-radius:20px;margin-top:10px;">
        <table class="auto-style18">
            <tr>
                <td class="auto-style2">
                    <asp:ImageButton ID="imgBtn_Logo" runat="server" Width="84px" Height="60px" ImageUrl="~/ImagenesHeader/Logo.png" OnClick="imgBtn_Logo_Click" />
                </td>
                <td class="auto-style4">
                    <asp:Label ID="lblNombreUsuario" runat="server"></asp:Label>
                </td>
                <td class="auto-style26">&nbsp;</td>
                <td class="auto-style27">&nbsp;</td>
                <td class="auto-style16"><strong>
                    <asp:HyperLink ID="hlUsuario" runat="server">[hlUsuario]</asp:HyperLink>
                    </strong></td>
                <td class="auto-style3">
                    <asp:ImageButton ID="imgBtn_Carrito" runat="server" CssClass="auto-style17" Height="50px" Width="43px" ImageUrl="~/ImagenesHeader/changuito.png" OnClick="imgBtn_Carrito_Click" />
                </td>
            </tr>
        </table>
       </div>
        <table class="auto-style1">
            <tr>
                <td class="auto-style8">&nbsp;</td>
                <td class="auto-style25">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style22"></td>
                <td class="auto-style23"></td>
                <td class="auto-style24">
                    <asp:Button ID="btnBorrarCarrito" runat="server" Text="Eliminar carrito" OnClick="btnBorrarCarrito_Click" OnClientClick="return confirm('¿Esta seguro que quiere vaciar el carrito?')"/>
                </td>
            </tr>
            <tr>
                <td class="auto-style8">&nbsp;</td>
                <td class="auto-style25">&nbsp;</td>
                <td class="auto-style3">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style9"></td>
                <td class="auto-style13">
                    <asp:GridView ID="grdProductosCarrito" runat="server" CssClass="auto-style17" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" OnRowDeleting="grdProductosCarrito_RowDeleting" Width="622px" OnRowCancelingEdit="grdProductosCarrito_RowCancelingEdit" OnRowEditing="grdProductosCarrito_RowEditing" OnRowUpdating="grdProductosCarrito_RowUpdating">
                        <AlternatingRowStyle BackColor="White" />
                        <Columns>
                            <asp:TemplateField HeaderText="Nombre">
                                <EditItemTemplate>
                                    <asp:Label ID="lbl_edit_Nombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lbl_grd_Nombre" runat="server" Text='<%# Bind("Nombre") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Precio">
                                <EditItemTemplate>
                                    <asp:Label ID="lbl_edit_Precio" runat="server" Text='<%# Bind("Precio") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lbl_grd_Precio" runat="server" Text='<%# Bind("Precio") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Cantidad">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txt_edit_Cantidad" runat="server" Text='<%# Bind("Cantidad") %>' TextMode="Number" OnTextChanged="txt_edit_Cantidad_TextChanged"></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lbl_grd_Cantidad" runat="server" Text='<%# Bind("Cantidad") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Total">
                                <EditItemTemplate>
                                    <asp:Label ID="lbl_edit_Total" runat="server" Text='<%# Bind("Total") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lbl_grd_Total" runat="server" Text='<%# Bind("Total") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                        <EditRowStyle BackColor="#2461BF" />
                        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                        <RowStyle BackColor="#EFF3FB" />
                        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                        <SortedAscendingCellStyle BackColor="#F5F7FB" />
                        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                        <SortedDescendingCellStyle BackColor="#E9EBEF" />
                        <SortedDescendingHeaderStyle BackColor="#4870BE" />
                    </asp:GridView>
                </td>
                <td class="auto-style11"></td>
            </tr>
            <tr>
                <td class="auto-style7"></td>
                <td class="auto-style14"></td>
                <td class="auto-style5"><strong>
                    <asp:Label ID="lblTotal" runat="server" CssClass="auto-style19" Text="Total precio: "></asp:Label>
                    </strong></td>
            </tr>
            <tr>
                <td class="auto-style8">&nbsp;</td>
                <td class="auto-style25">
                    <asp:Button ID="btnConfirmarCompra" runat="server" Text="Confirmar Compra" OnClick="btnConfirmarCompra_Click" />
                </td>
                <td>&nbsp;</td>
            </tr>
        </table>
    </form>
</body>
</html>
